### ISSUE TITLE
Error about SOON benchmark submission

### ISSUE THREAD

**Issue by MuMuJun97** [cshizhe/VLN-DUET#14]
Hi, @cshizhe. Thanks for your great work!
When I use your code `run_soon.sh` to generate `submit_test.json` and submit the json file to SOON benchmark https://eval.ai/web/challenges/challenge-page/1275, I get the following error:
```shell
Stderr file:
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 508, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmppo8pw22p/compute/challenge_data/challenge_1275/main.py", line 262, in evaluate
    score_summary = ev.score(submit_data)
  File "/tmp/tmppo8pw22p/compute/challenge_data/challenge_1275/main.py", line 174, in score
    self._score_item(item['instr_id'], trajectory['path'],
TypeError: string indices must be integers
```

My submitted json file is shown as following:
```json
[
  {
        "instr_id": "4-0_0",
        "trajectory": {
            "obj_elevation": [
                0.42584675638572644
            ],
            "obj_heading": [
                0.7852983158100036
            ],
            "path": [
                [
                    "13ae1603f381466a86b3d1dcc884366c"
                ],
                ...
            ]
        }
    },
    ... 
```

I want to know the difference between my submitted file and the correct json file.

Besides, what's the difference between `submit_test.json` and `submit_test_v2.json` ? 
In https://github.com/cshizhe/VLN-DUET/blob/7a8a5dee383e638767878da30ad23cbdca97f53b/map_nav_src/soon/main.py#L258
```python
        if default_gpu:
            if 'test_v2' not in env_name:
                score_summary, _ = env.eval_metrics(preds)
                loss_str = "Env name: %s" % env_name
                for metric, val in score_summary.items():
                    loss_str += ', %s: %.2f' % (metric, val)
                write_to_record_file(loss_str+'\n', record_file)

            if args.submit:
                json.dump(
                    preds,
                    open(os.path.join(args.pred_dir, "submit_%s.json" % env_name), 'w'),
                    sort_keys=True, indent=4, separators=(',', ': ')
                )
```

**Comment by cshizhe** [comment]
I would suggest you to check the latest required format for the leaderboard submission. The format might be changed.
